# Generated by Django 6.0.6 on 2026-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("honorific", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=64)),
                ("based_in", models.CharField(blank=True, max_length=255)),
                ("nationality", models.CharField(blank=True, max_length=8)),
                ("linkedin", models.URLField(blank=True, max_length=512)),
                ("locale", models.CharField(default="en", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
