# Generated by Django 6.0.6 on 2026-06-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "Single choice"),
                            ("multi", "Multiple choice"),
                            ("ordered", "Ordered (ranked)"),
                            ("text", "Text"),
                            ("email", "Email"),
                            ("tel", "Telephone"),
                            ("url", "URL"),
                            ("country", "Country"),
                            ("select", "Select"),
                        ],
                        max_length=16,
                    ),
                ),
                ("screen", models.CharField(blank=True, max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=False)),
                ("max_select", models.PositiveIntegerField(blank=True, null=True)),
                ("has_other", models.BooleanField(default=False)),
                ("label_en", models.CharField(blank=True, max_length=512)),
                ("label_ar", models.CharField(blank=True, max_length=512)),
                ("help_en", models.CharField(blank=True, max_length=512)),
                ("help_ar", models.CharField(blank=True, max_length=512)),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.formversion",
                    ),
                ),
            ],
            options={
                "ordering": ["form_version", "order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                ("label_en", models.CharField(blank=True, max_length=512)),
                ("label_ar", models.CharField(blank=True, max_length=512)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order"],
            },
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("form_version", "code"), name="uniq_question_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("question", "code"), name="uniq_option_per_question"
            ),
        ),
    ]
