# Generated by Django 6.0.6 on 2026-06-21 17:40

import django.db.models.deletion
import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("invited_by", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("opened", "Opened"),
                            ("submitted", "Submitted"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=5)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=onboarding.models.generate_reference,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("shortlisted", "Shortlisted"),
                            ("on_hold", "On hold"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=5)),
                ("ack_intro", models.BooleanField(default=False)),
                ("ack_consent", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="catalog.formversion",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="onboarding.invitation",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_code", models.CharField(db_index=True, max_length=64)),
                (
                    "option_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("text_value", models.TextField(blank=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("other_text", models.TextField(blank=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="onboarding.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["submission", "question_code", "rank", "id"],
                "indexes": [
                    models.Index(
                        fields=["question_code", "option_code"],
                        name="onboarding__questio_262f4b_idx",
                    )
                ],
            },
        ),
    ]
